### ISSUE TITLE
Gradle's "tools:overrideLibrary" doesn't work with IjkPlayer anymore

### ISSUE THREAD

**Issue by mvasilchuk** [Bilibili/ijkplayer#1222]
Since commit https://github.com/Bilibili/ijkplayer/commit/506d5bb299e88c6e6f4f6c9c288f3c44f5da826a it's not possible to use IjkPlayer in apps that have 
`<uses-sdk  tools:overrideLibrary="lib_name"/>`
 in manifest. For example, this tag is required if you want to use android.support.v17.leanback library and your app's minSdkVersion is less than 17.

**Comment by bbcallen** [comment]
I thought it only affect lint.

**Comment by bbcallen** [comment]
Reverted.

**Comment by mikecharif14** [comment]
Hey I just found a bug on the stb emulator after the updates, we can't configure keys, the action key list does not have a drop down list so we can pick what buttons are for what like for example I cant press yellow key on android box and link it to yellow button please let me know if I am doing somethin wrong, Im sure its abug because if I download an old version like 0.6 it works but does not work on 0.8 and so on.

**Comment by mvasilchuk** [comment]
You must be write in the wrong thread. It's a repository of Ijk player, not of the stb emulator.

**Comment by mikecharif14** [comment]
are you the stb emulator programmer tho ? i found a bug
