### ISSUE TITLE
Playing streaming video type is https.

### ISSUE THREAD

**Issue by fantasy1022** [Bilibili/ijkplayer#16]
Hello, 
      Thank you for awesome job to do this player. I have question about playing streaming
video which protocol is https. This would cause playing error. Does it has any solution for this function? Thank you!

**Comment by bbcallen** [comment]
Tested

**Comment by Zo2m4bie** [comment]
@fantasy1022 
Hello. I know it's kind of old question but I try to compile ffmpeg with openssl. And I see you mentioned above about adding --enable-openssl and adding openssl folder to compile-ffmpeg script in FF_CFG_FLAGS, FF_CFLAGS. I found at do-compile-ffmpeg this script:

```

if [ -f "${FF_DEP_OPENSSL_LIB}/libssl.a" ]; then
echo "then called"
  FF_CFG_FLAGS="$FF_CFG_FLAGS --enable-nonfree"
    FF_CFG_FLAGS="$FF_CFG_FLAGS --enable-openssl"

    FF_CFLAGS="$FF_CFLAGS -I${FF_DEP_OPENSSL_INC}"
    FF_DEP_LIBS="-L${FF_DEP_OPENSSL_LIB} -lssl -lcrypto"
fi 
```

As I understand this script adds openssl lib to FF_CFG_FLAGS and FF_CFLAGS. So ffmpeg has to compile with openssl, but my https streams still don't work. Unfortunately I cannot work with your compiled lib, because I made some changes in ffmpeg code. Can you provide some steps how to compile lib with openssl?
Thank you!
