### ISSUE TITLE
从ff3.0--ijk0.5.0更新到ff3.1--ijk0.6.0遇到点播flv拖拉问题

### ISSUE THREAD

**Issue by wuhuangpeng** [Bilibili/ijkplayer#1796]
从ff3.0--ijk0.5.0更新到ff3.1--ijk0.6.0后，发现点播flv的进度条拖拉有问题，而m3u8、avi、rmvb、MP4等格式都是正常的。
问题描述：
    原先用ff3.0--ijk0.5.0是正常的，更新到`ff3.1--ijk0.6.0`后，用ijkplayer点播flv时发现问题。当拖拉进度条时（比如从10钟分拖到40分钟），开始进入缓冲，但是要等待非常久（数分钟）才能开始播放。
    抓包发现，在拖动进度条时，ff3.0--ijk0.5.0版本会发一个http range请求，然后立马开始播放。而ff3.1--ijk0.6.0会先发一个range值不正确的http range请求，过了好久后（数分钟）会发第二个http range请求（正确的），然后开始播放。
    不知大神这是否已知问题，万望回复。

**Comment by xinzhengzhang** [comment]
@wuhuangpeng 
This issue has been fixed in [cd141e7](http://git.videolan.org/?p=ffmpeg.git;a=commit;h=cd141e71bd3441ac9b7b720b934b7d4d85a75355) and [ad14aab](http://git.videolan.org/?p=ffmpeg.git;a=commit;h=ad14aab3b4f88cdb6c2a3f8877c578e5a8042f1d). 
It will be released in 0.6.1 (it will take several day).
If you are in a hurry to fix it, cherry-pick these two commits manually.

**Comment by wuhuangpeng** [comment]
非常感谢哈，期待0.6.1
