### ISSUE TITLE
High quality video playback

### ISSUE THREAD

**Issue by jpoloczek** [Bilibili/ijkplayer#212]
Hi BbCallen,

I appreciate your work, it's great video player with lot's of features.

Would you be so kind to tell me when following features will be available:

Video decoders:
1) x264 - H.264 AVC decoder (includes 10-bit mode for high-quality applications)
2) x265 decoder for 4K videos. What profiles will be supported?
3) Speedcontrol to increase decoding complexity when CPU capacity is available
4) Multicore/multithread video decoding in CPU mode

Video Filters:
5) 10-bit to 8-bit dithering
6) 4:2:2 to 4:2:0 resampling using libswscale
7) Filters via libavfilter
8) Noise reduction, etc.
9) Handling for 3DTV formats

Best regards,
Janusz

**Comment by bbcallen** [comment]
Video decoders:
1. h264 is supported, 10-bit render is not.
2. h265 support is removed, you can modify config/module-lite.h to enable it. supported profiles is depending on FFmpeg.
3. speed control is not available.
4. h264 multithread is enabled at runtime by FFmpeg.

Video Filters:
5. No.
6. libswscale is supported.
7. Removed, not fast enough for android/ios due to extra memory copy.
8. No.
9. No.
