### ISSUE TITLE
Is a good idea to enable CONFIG_AVFILTER to support ffmpeg filters in ijkplayer?

### ISSUE THREAD

**Issue by wanzhang** [Bilibili/ijkplayer#295]
I add "--enable-avfilter" flags when compile ffmpeg library, and is OK. But I got lots of compile errors when enable CONFIG_AVFILTER to compile ijkplayer library, and I am very confused with FFP_MERGE macro.

**Comment by bbcallen** [comment]
CONFIG_AVFILTER is not under maintain in ijkplayer. It need extra memcpy in decode-display pipeline.

FFP_MERGE keeps original ffplay.c code to avoid large trunk of diff while merging code from upstream.

**Comment by wanzhang** [comment]
Thanks for reply. I am trying to add-filters in ijkPlayer, is there a  large risk?  any suggestions are welcome.

**Comment by bbcallen** [comment]
1. Both MediaCodec and VideoToolbox are not compatible with video-filters, due to zero-copy render, so avcodec is your only choice. Video-filters also introduce extra memcpy per frame.

2. Find out the hash of ffplay.c merged by ff_ffplay.c
```
git log ijkmedia/ijkplayer/ff_ffplay.c | grep merge
```

3. Find out removed codes guarded by CONFIG_AVFILTER and merge them back.
```
diff ff_ffplay.c ffplay.c
```

4. If you need subtitle filter, the whole subtitle pipeline needs to be merged back, too.

5. Work would be done 99% after all compile errors are fixed.

**Comment by bbcallen** [comment]
And I don't think it's a good idea to enable CONFIG_AVFILTER on mobile devices for videos above 720p HD

**Comment by wanzhang** [comment]
Thanks again. Actually, I'm going to preview 480*480 video with filtering effects on android devices
in real time. I will do some tests, and hope it works well.
