### ISSUE TITLE
我要吐槽ijkplayer

### ISSUE THREAD

**Issue by goodcyg** [Bilibili/ijkplayer#3282]
ijkplayer对开源界，乃至大家贡献不言而喻。好处就不说了。
直接说不足吧？
1.整个代码缺少必要注释。
2.虽然ijkplayer是开源，但是开源项目也要讲质量和效率啊，能不能把ijkplayer开源做的更好？对在github上提出的问题和疑惑，不能及时的给予解答，即使解答了，也是寥寥的几个字，没有做到详细直接的解答？如果解答不了，请给个指导方向？
3.大家来提问是对ijkplayer的喜爱和支持，希望ijkplayer官方对以上两点做个改善？如果觉得我提的意见，有点价值的老铁们，把这个帖子顶起来！

**Comment by bbcallen** [comment]
Patch welcome.

**Comment by shanchieh** [comment]
如果這是收費的，要求這些很合理。但是免費的提供給大家使用已經是非常了不起，官方沒有收取費用，他們沒有義務解決大家的疑問，如果提出的問題，他們如果有時間詳細的回答，我會很感謝他們，但是即使他們不回答，或者回答不詳細，我也沒權利要求他們。　再說　Source Code 就是最好的文件。他們已經是 100% 的開放源碼，遇到問題，只好就自己去追蹤源碼。

**Comment by jununfly** [comment]
People feeds kid，help yourself.

**Comment by jununfly** [comment]
People feeds kid，help yourself.

**Comment by goodcyg** [comment]
ijkplayer开源官方的目的是想把ijkplayer做的更好，如果说我提的这点建议，他们不在乎的话，完全可以不理会。来这里提问还是希望得到一点帮助，不是人人都是都是高手，都能扒拉出源码来，解决掉自己的问题？

**Comment by bbcallen** [comment]
ijkplayer is open source, because it depends on FFmpeg which is licensed under LGPL, no more, no less. We develop and fix what we need, no more, no less.

Yes, we don't care issues we have no interest in, eg. "make ijkplayer better".

If you want it to be better in your way, fork it, or submit pull request. That's the point of open source.
