### ISSUE TITLE
视频花屏

### ISSUE THREAD

**Issue by cracj** [Bilibili/ijkplayer#386]
您好，在使用您的项目的时候遇到这样的问题(如图)
![img_0502](https://cloud.githubusercontent.com/assets/7333328/9085094/58c603dc-3bac-11e5-83d4-4d4418a9a976.jpg)
碰到这种效果是什么原因啊？我的视频是是RTMP的，用的是软解码。视频源没有问题。

**Comment by Android4MediaPlayer** [comment]
贴出你的播放地址，是偶尔花屏还是一直会

**Comment by cracj** [comment]
偶尔这样厉害地花屏，平常状态下脸部有马赛克的感觉，动的地方都有马赛克的感觉。我的那个地址是内网的，外部的地址也有类似问题，我贴出一个外部地址：rtmp://live.hkstv.hk.lxdns.com/live/hks

**Comment by Android4MediaPlayer** [comment]
你用VLC播放呢或者先换着用硬解码测试下

**Comment by cracj** [comment]
我用了硬解码效果会好些，但我们项目的视频没法用硬解码，去找了服务器，他们说给出的RTMP视频流是没有SPS和PPS的。所以我们设备硬解码不出来该流，服务器给出的建议是自己手动添加上这个头，但我看了一天代码也不知道在哪添加合适，实在没办法了只有来麻烦你们了

**Comment by Android4MediaPlayer** [comment]
“我用了硬解码效果会好些”是用什么播放的

**Comment by garymabin** [comment]
rtmp://live.hkstv.hk.lxdns.com/live/hks, 就这个地址，我这边用ijkplayer试下来，是没有看出来有马赛克的,另外目前的项目在使用ijkplayer播放rtmp流的时候，除了在流切换的时候，因为残留问题可能存在马赛克，常时状态的马赛克也是没怎么见到的

**Comment by cracj** [comment]
我刚才用ijkplayer分别用软解码和硬解码播放rtmp://live.hkstv.hk.lxdns.com/live/hks，结果显示硬解码效果好得多，没有了我刚才说的那个问题，但现在的问题是我们项目中使用的RTMP流用ijkplayer可以软解码，但用硬解码解码会失败，失败的原因是因为我们项目中的RTMP流缺少SPS和PPS。我想试着在ijkplayer中手动添加SPS和PPS。我应该怎么添加SPS和PPS才能使ijkplayer能硬解码我们的RTMP流？

**Comment by cracj** [comment]
@Android4MediaPlayer @garymabin 我这种情况能不能搞？

**Comment by garymabin** [comment]
@cracj 可以尝试在收到的第一个I帧上加上SPS跟PPS参数，我帮忙看看怎么加好了..

**Comment by cracj** [comment]
@garymabin 万分感激！！！

**Comment by Android4MediaPlayer** [comment]
@cracj 你是说你服务器压根就不会有sps和pps数据吗? 是出于啥考虑呢 这个是解码必须得参数啊 像RTSP流要么在SDP里要么在第一个I帧前面的

**Comment by Android4MediaPlayer** [comment]
rtmp的话应该也有自己的协议规则，我不是太了解。

**Comment by cracj** [comment]
他们给了我这个头：
#define SPS "\x67\x64\x00\x15\xac\xb3\x03\xc1\x7f\xcb\x08\x00\x00\x03\x00\x08\x00\x00\x03\x01\x94\x78\xb1\x73\x40" 
#define SPSLEN 25 
#define PPS "\x68\xe9\x73\x2c\x8b" 
#define PPSLEN 5

**Comment by bbcallen** [comment]
mp.setAvCodecOption("skip_loop_filter", 0)

**Comment by cracj** [comment]
@Android4MediaPlayer @garymabin 这个头该加在哪儿？我也试试

**Comment by cracj** [comment]
@bbcallen 没找到setAvCodecOption这个方法，忘了说了，我的是iOS版本的

**Comment by Zard1096** [comment]
对应iOS方法为ijkmp_set_codec_option()

**Comment by cracj** [comment]
@Zard1096 也没有找到ijkmp_set_codec_option()，最接近的是这个方法-(void)setCodecOptionValue:(NSString *)value forKey:(NSString *)key

**Comment by Android4MediaPlayer** [comment]
void ijkmp_set_option(IjkMediaPlayer *mp, int opt_category, const char *name, const char *value)找下这个方法

**Comment by garymabin** [comment]
[self setCodecOptionIntValue:IJK_AVDISCARD_DEFAULT forKey:@"skip_loop_filter"];

**Comment by cracj** [comment]
@各位大神，还是没法解码
ijkmp_set_format_callback(0x10d5e5, 0x17ec4a20)
ijkmp_set_format_callback()=void
ijkmp_set_option_int(start-on-prepared, 1)
ijkmp_set_option_int()=void
ijkmp_ios_set_view(glView=0x17d36c10)
ijkmp_ios_set_view(glView=0x17d36c10)=void
ijkmp_set_option(overlay-format, fcc-i420)
ijkmp_set_option()=void
ijkmp_set_option_int(framedrop, 5)
ijkmp_set_option_int()=void
ijkmp_set_option_int(max-fps, 30)
ijkmp_set_option_int()=void
ijkmp_set_option_int(video-pictq-size, 3)
ijkmp_set_option_int()=void
ijkmp_set_option_int(videotoolbox-max-frame-width, 960)
ijkmp_set_option_int()=void
ijkmp_set_option_int(videotoolbox, 1)
ijkmp_set_option_int()=void
ijkmp_set_option(user-agent, ijkplayer)
ijkmp_set_option()=void
ijkmp_set_option_int(reconnect, 1)
ijkmp_set_option_int()=void
ijkmp_set_option_int(skip_loop_filter, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(skip_frame, 8)
ijkmp_set_option_int()=void
ijkmp_set_data_source(url="rtmp://222.73.33.119/live/3659787?userId=3011577106&roomId=3659787")
ijkmp_set_data_source(url="rtmp://222.73.33.119/live/3659787?userId=3011577106&roomId=3659787")=0
ijkmp_set_option(safe, 0)
ijkmp_set_option()=void
ijkmp_prepare_async()
===== options =====
player-opts : start-on-prepared            = 1
player-opts : overlay-format               = fcc-i420
player-opts : framedrop                    = 5
player-opts : max-fps                      = 30
player-opts : video-pictq-size             = 3
player-opts : videotoolbox-max-frame-width = 960
player-opts : videotoolbox                 = 1
format-opts : user-agent                   = ijkplayer
format-opts : reconnect                    = 1
format-opts : safe                         = 0
codec-opts  : skip_loop_filter             = 0
codec-opts  : skip_frame                   = 8
===================
ijkmp_prepare_async()=0
ijkmp_start()
ijkmp_start()=-3
2015-08-06 11:01:58.175 FFmpeg[6590:718381] IJKSDLGLView:applicationDidBecomeActive: 0
2015-08-06 11:01:58.177 FFmpeg[6590:718381] IJKFFMoviePlayerController:applicationDidBecomeActive: 0
Handshaking...
Type answer 3
Server version 0.0.0.0
Proto = rtmp, path = /live/3659787?userId=3011577106&roomId=3659787, app = live, fname = 3659787?userId=3011577106&roomId=3659787
Server bandwidth = 2500000
Client bandwidth = 2500000
Creating stream...
Sending play command for '3659787?userId=3011577106&roomId=3659787'
Server error: call to function _checkbw failed
Format flv probed with size=2048 and score=100
Option user-agent not found.
Before avformat_find_stream_info() pos: 13 bytes read:22902 seeks:0
Unknown type |RtmpSampleAccess
AVC: Consumed only 1 bytes instead of 22429
AVC: Consumed only 1 bytes instead of 1223
AVC: Consumed only 1 bytes instead of 954
AVC: Consumed only 1 bytes instead of 1560
AVC: Consumed only 1 bytes instead of 1623
AVC: Consumed only 1 bytes instead of 1224
AVC: Consumed only 1 bytes instead of 1487
Stream discovered after head already parsed
All info found
rfps: 15.000000 0.019600
rfps: 15.083333 0.004726
rfps: 15.083333 0.004726
rfps: 15.166667 0.000042
rfps: 15.250000 0.005545
rfps: 15.250000 0.005545
After avformat_find_stream_info() pos: 91377 bytes read:91377 seeks:0 frames:47
max_frame_duration: 3600.000
Input #0, flv, from 'rtmp://222.73.33.119/live/3659787?userId=3011577106&roomId=3659787':
  Metadata:
    Server          : C++ RTMP Media Server (www.rtmpd.com)
    audiochannels   : 2
    audioinputvolume: 46
    avclevel        : 21
    avcprofile      : 100
    bandwidth       : 0
    copyright       : 
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0, 46, 1/1000: Video: h264, 5 reference frames, yuv420p(left), 480x360 (480x368), 1/50, 25 fps, 15.17 tbr, 1k tbn, 50 tbc
    Stream #0:1, 1, 1/1000: Audio: mp3, 32000 Hz, stereo, s16p, 80 kb/s
aout_open_audio()
AudioCodec: avcodec, mp3
aout_pause_audio(0)
detected 2 logical cores
init_videotoolbox - using avcC atom of size(41), ref_frames(5)after scale width 480 height 360 
m_max_ref_frames 5 
flushed last keyframe pts 0 
fps: 25.000000 (normal)
fps: 15.166667 (normal)
2015-08-06 11:01:58.847 FFmpeg[6590:718381] FFP_MSG_VIDEO_DECODER_OPEN: true
ijkmp_get_msg: FFP_MSG_PREPARED
2015-08-06 11:01:58.850 FFmpeg[6590:718381] FFP_MSG_PREPARED:
ijkmp_get_meta_l
ijkmp_get_meta_l()=void
2015-08-06 11:01:58.851 FFmpeg[6590:718381] fps in meta 25.000000
2015-08-06 11:01:58.852 FFmpeg[6590:718381] mediaIsPreparedToPlayDidChange
2015-08-06 11:01:58.853 FFmpeg[6590:718381] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3
2015-08-06 11:01:58.853 FFmpeg[6590:718381] moviePlayBackStateDidChange 1: playing
2015-08-06 11:01:58.854 FFmpeg[6590:718381] FFP_MSG_VIDEO_SIZE_CHANGED: 480, 360
2015-08-06 11:01:58.856 FFmpeg[6590:718381] FFP_MSG_SAR_CHANGED: 0, 1
ffp_toggle_buffering_l: start
aout_pause_audio(1)
2015-08-06 11:01:58.897 FFmpeg[6590:718381] FFP_MSG_BUFFERING_START:
2015-08-06 11:01:58.898 FFmpeg[6590:718381] loadStateDidChange: MPMovieLoadStateStalled: 4
after scale width 480 height 360 
decodeFrame -12911 kVTVideoDecoderMalfunctionErr
decode callback -12909 kVTVideoDecoderBadDataErr
sample_info_recycle, multiple frames in same sample 0 / 1
unknown SEI type 24
unknown SEI type 159
SEI type 70 size 816 truncated at 696
missing picture in access unit with size 244
Sending bytes read report
missing picture in access unit with size 432
missing picture in access unit with size 398
Sending bytes read report
missing picture in access unit with size 265
missing picture in access unit with size 180
missing picture in access unit with size 851
missing picture in access unit with size 408
missing picture in access unit with size 305
Sending bytes read report
missing picture in access unit with size 524
Sending bytes read report
missing picture in access unit with size 100
missing picture in access unit with size 795

**Comment by Android4MediaPlayer** [comment]
@cracj 用软解码，把skip_loop_filter设置为0，测试下

**Comment by cracj** [comment]
[options setSkipLoopFilter:IJK_AVDISCARD_DEFAULT];用软解，我再试试效果怎么样

**Comment by cracj** [comment]
效果好多了，谢谢各位大神们！谁能告诉我接收到帧的代码在哪儿？我争取加那个头试试，那样效果可能会更好。

**Comment by garymabin** [comment]
@cracj 你可能得提供一些因为没有PPS，SPS参数导致硬解码失败的日志，因为我仔细看了一下，硬解的时候，SPS跟PPS参数是会通过上下文传递到MediaCodec的，也就是即便是RTMP流中只有第一帧带了PPS，SPS参数，只要上下文中有相关参数，硬解也是可以进行的..

**Comment by mars-rover** [comment]
@garymabin 我给你看看这个硬解失败的日志：
ijkmp_set_format_callback(0x1f5e5, 0x156237c0)
ijkmp_set_format_callback()=void
ijkmp_set_option_int(start-on-prepared, 1)
ijkmp_set_option_int()=void
ijkmp_ios_set_view(glView=0x155c2ba0)
ijkmp_ios_set_view(glView=0x155c2ba0)=void
ijkmp_set_option(overlay-format, fcc-i420)
ijkmp_set_option()=void
ijkmp_set_option_int(framedrop, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(max-fps, 30)
ijkmp_set_option_int()=void
ijkmp_set_option_int(video-pictq-size, 3)
ijkmp_set_option_int()=void
ijkmp_set_option_int(videotoolbox-max-frame-width, 960)
ijkmp_set_option_int()=void
ijkmp_set_option_int(videotoolbox, 1)
ijkmp_set_option_int()=void
ijkmp_set_option(user-agent, ijkplayer)
ijkmp_set_option()=void
ijkmp_set_option_int(reconnect, 1)
ijkmp_set_option_int()=void
ijkmp_set_option_int(skip_loop_filter, 0)
ijkmp_set_option_int()=void
ijkmp_set_option_int(skip_frame, 8)
ijkmp_set_option_int()=void
ijkmp_set_data_source(url="rtmp://222.73.33.119/live/3659787?userId=3011577106&roomId=3659787")
ijkmp_set_data_source(url="rtmp://222.73.33.119/live/3659787?userId=3011577106&roomId=3659787")=0
ijkmp_set_option(safe, 0)
ijkmp_set_option()=void
ijkmp_prepare_async()
===== options =====
player-opts : start-on-prepared            = 1
player-opts : overlay-format               = fcc-i420
player-opts : framedrop                    = 0
player-opts : max-fps                      = 30
player-opts : video-pictq-size             = 3
player-opts : videotoolbox-max-frame-width = 960
player-opts : videotoolbox                 = 1
format-opts : user-agent                   = ijkplayer
format-opts : reconnect                    = 1
format-opts : safe                         = 0
codec-opts  : skip_loop_filter             = 0
codec-opts  : skip_frame                   = 8
===================
ijkmp_prepare_async()=0
ijkmp_start()
ijkmp_start()=-3
2015-08-06 15:17:45.327 FFmpeg[7373:766542] IJKSDLGLView:applicationDidBecomeActive: 0
2015-08-06 15:17:45.335 FFmpeg[7373:766542] IJKFFMoviePlayerController:applicationDidBecomeActive: 0
Handshaking...
Type answer 3
Server version 0.0.0.0
Proto = rtmp, path = /live/3659787?userId=3011577106&roomId=3659787, app = live, fname = 3659787?userId=3011577106&roomId=3659787
Server bandwidth = 2500000
Client bandwidth = 2500000
Creating stream...
Sending play command for '3659787?userId=3011577106&roomId=3659787'
Server error: call to function _checkbw failed
Format flv probed with size=2048 and score=100
Option user-agent not found.
Before avformat_find_stream_info() pos: 13 bytes read:21261 seeks:0
Unknown type |RtmpSampleAccess
AVC: Consumed only 1 bytes instead of 20788
AVC: Consumed only 1 bytes instead of 252
AVC: Consumed only 1 bytes instead of 456
AVC: Consumed only 1 bytes instead of 551
AVC: Consumed only 1 bytes instead of 538
AVC: Consumed only 1 bytes instead of 674
AVC: Consumed only 1 bytes instead of 738
Stream discovered after head already parsed
All info found
rfps: 23.166667 0.013599
rfps: 23.166667 0.013599
rfps: 23.250000 0.006165
rfps: 23.250000 0.006165
rfps: 23.333333 0.002114
rfps: 23.416667 0.001445
rfps: 23.500000 0.004158
rfps: 23.500000 0.004158
rfps: 23.583333 0.010254
rfps: 23.583333 0.010254
rfps: 23.666667 0.019732
rfps: 23.666667 0.019732
After avformat_find_stream_info() pos: 91086 bytes read:91086 seeks:0 frames:65
max_frame_duration: 3600.000
Input #0, flv, from 'rtmp://222.73.33.119/live/3659787?userId=3011577106&roomId=3659787':
  Metadata:
    Server          : C++ RTMP Media Server (www.rtmpd.com)
    audiochannels   : 2
    audioinputvolume: 46
    avclevel        : 21
    avcprofile      : 100
    bandwidth       : 0
    copyright       : 
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0, 41, 1/1000: Video: h264, 5 reference frames, yuv420p(left), 480x360 (480x368), 1/50, 25 fps, 23.42 tbr, 1k tbn, 50 tbc
    Stream #0:1, 24, 1/1000: Audio: mp3, 32000 Hz, stereo, s16p, 80 kb/s
aout_open_audio()
AudioCodec: avcodec, mp3
aout_pause_audio(0)
detected 2 logical cores
init_videotoolbox - using avcC atom of size(41), ref_frames(5)after scale width 480 height 360 
m_max_ref_frames 5 
fps: 25.000000 (normal)
fps: 23.416667 (normal)
ijkmp_get_msg: FFP_MSG_PREPARED
flushed last keyframe pts 0 
2015-08-06 15:17:46.772 FFmpeg[7373:766542] FFP_MSG_VIDEO_DECODER_OPEN: true
2015-08-06 15:17:46.773 FFmpeg[7373:766542] FFP_MSG_PREPARED:
ijkmp_get_meta_l
ijkmp_get_meta_l()=void
2015-08-06 15:17:46.775 FFmpeg[7373:766542] fps in meta 25.000000
2015-08-06 15:17:46.776 FFmpeg[7373:766542] mediaIsPreparedToPlayDidChange
2015-08-06 15:17:46.777 FFmpeg[7373:766542] loadStateDidChange: MPMovieLoadStatePlaythroughOK: 3
2015-08-06 15:17:46.778 FFmpeg[7373:766542] FFP_MSG_VIDEO_SIZE_CHANGED: 480, 360
2015-08-06 15:17:46.778 FFmpeg[7373:766542] FFP_MSG_SAR_CHANGED: 0, 1
2015-08-06 15:17:46.779 FFmpeg[7373:766542] moviePlayBackStateDidChange 1: playing
after scale width 480 height 360 
decodeFrame -12911 kVTVideoDecoderMalfunctionErr
decode callback -12909 kVTVideoDecoderBadDataErr
sample_info_recycle, multiple frames in same sample 0 / 1
sps_id 2 out of range
missing picture in access unit with size 150
Sending bytes read report

**Comment by garymabin** [comment]
@cracj  抱歉，才发现这个是IOS下的情形..我刚才说的是Android的处理，IOS下面我就不太清楚了

**Comment by mars-rover** [comment]
没事，是我没描述清楚，你能帮我指出 “收到的第一个I帧上加上SPS跟PPS参数” 中的收到第一个帧的代码吗？我对ijkplayer不太熟，没能找到那处代码。

**Comment by mars-rover** [comment]
@garymabin 没事，是我没描述清楚，你能帮我指出 “收到的第一个I帧上加上SPS跟PPS参数” 中的收到第一个帧的代码吗？我对ijkplayer不太熟，没能找到那处代码。

**Comment by garymabin** [comment]
[这里](https://github.com/Bilibili/ijkplayer/blob/master/ijkmedia/ijkplayer/ff_ffplay.c#L1619)，每一帧视频数据都是这里获取到的,具体要怎么修改AVFrame，可能你还是需要小心一些

**Comment by libinok** [comment]
> @cracj 可以尝试在收到的第一个I帧上加上SPS跟PPS参数，我帮忙看看怎么加好了..

大哥能帮忙看看花屏问题吗 有深入了解不
