### ISSUE TITLE
Feature request: Multiple audio tracks

### ISSUE THREAD

**Issue by moster67** [Bilibili/ijkplayer#72]
Many thanks for this excellent library. Works great. One feature I miss is the possibility to have multiple audio tracks, very common in DVB using for example mpeg2video. Hope you eventually will have time to implement it. Thanks.

**Comment by Peterede** [comment]
The stream_cycle_channel function looks like it may work, it is just a matter of exporting the function so it can be called from java:

02677 static void stream_cycle_channel(VideoState *is, int codec_type)
02678 {
02679     AVFormatContext *ic = is->ic;
02680     int start_index, stream_index;
02681     AVStream *st;
02682 
02683     if (codec_type == AVMEDIA_TYPE_VIDEO)
02684         start_index = is->video_stream;
02685     else if (codec_type == AVMEDIA_TYPE_AUDIO)
02686         start_index = is->audio_stream;
02687     else
02688         start_index = is->subtitle_stream;
02689     if (start_index < (codec_type == AVMEDIA_TYPE_SUBTITLE ? -1 : 0))
02690         return;
02691     stream_index = start_index;
02692     for(;;) {
02693         if (++stream_index >= is->ic->nb_streams)
02694         {
02695             if (codec_type == AVMEDIA_TYPE_SUBTITLE)
02696             {
02697                 stream_index = -1;
02698                 goto the_end;
02699             } else
02700                 stream_index = 0;
02701         }
02702         if (stream_index == start_index)
02703             return;
02704         st = ic->streams[stream_index];
02705         if (st->codec->codec_type == codec_type) {
02706             /* check that parameters are OK */
02707             switch(codec_type) {
02708             case AVMEDIA_TYPE_AUDIO:
02709                 if (st->codec->sample_rate != 0 &&
02710                     st->codec->channels != 0)
02711                     goto the_end;
02712                 break;
02713             case AVMEDIA_TYPE_VIDEO:
02714             case AVMEDIA_TYPE_SUBTITLE:
02715                 goto the_end;
02716             default:
02717                 break;
02718             }
02719         }
02720     }
02721  the_end:
02722     stream_component_close(is, start_index);
02723     stream_component_open(is, stream_index);
02724 }

It would be good to have this so the track index can be specified.  It could be implemented so that it mirrors the function of the android mediaplayer function:

public void selectTrack (int index)

**Comment by Peterede** [comment]
I have added functions to ff_ffplay.c to select the index and also to get the number of tracks:

int ffp_select_track_l(FFPlayer *ffp, long index)
{
    assert(ffp);
    VideoState *is = ffp->is;
    int total = 0;
    if (!is)
        return EIJK_NULL_IS_PTR;

	AVFormatContext *ic = is->ic;
	int start_index, stream_index;
	AVStream *st;
	int codec_type = AVMEDIA_TYPE_AUDIO;
	
	if (codec_type == AVMEDIA_TYPE_VIDEO)
		start_index = is->video_stream;
	else if (codec_type == AVMEDIA_TYPE_AUDIO)
		start_index = is->audio_stream;
	/*else
		start_index = is->subtitle_stream;
	if (start_index < (codec_type == AVMEDIA_TYPE_SUBTITLE ? -1 : 0))
		return;*/
	
	for (stream_index = 0; stream_index < is->ic->nb_streams; stream_index++)
	{
		st = ic->streams[stream_index];
		if (st->codec->codec_type == codec_type) {
			/* check that parameters are OK */
			switch(codec_type) {
				case AVMEDIA_TYPE_AUDIO:
				if (st->codec->sample_rate != 0 &&
				st->codec->channels != 0)
				total++;
				if (total == index)
					goto the_end;
				break;
				
			}
		}
	}
	
	the_end:
	stream_component_close(ffp, start_index);
	stream_component_open(ffp, stream_index);
}

int ffp_get_track_info_l(FFPlayer *ffp)
{
    assert(ffp);
    VideoState *is = ffp->is;
    int total = 0;
    if (!is)
        return EIJK_NULL_IS_PTR;

	AVFormatContext *ic = is->ic;
	int stream_index;
	AVStream *st;
	int codec_type = AVMEDIA_TYPE_AUDIO;
	
	for (stream_index = 0; stream_index < is->ic->nb_streams; stream_index++)
	{
		st = ic->streams[stream_index];
		if (st->codec->codec_type == codec_type) {
			/* check that parameters are OK */
			switch(codec_type) {
				case AVMEDIA_TYPE_AUDIO:
				if (st->codec->sample_rate != 0 &&
				st->codec->channels != 0)
				total++;
				break;
				
			}
		}
	}
	
	return total;
}

**Comment by bbcallen** [comment]
hw-decoder is not good for this feature.

**Comment by NikmanSergey** [comment]
Hi! Thanks for the Great library!
I'd like to add audio track selection feature as well.
You told this implementation (by Peterede) will not work with MediaCodec?
Could you, please, tell how this feature can be implemented when using MediaCodec mode?
Thanks again!
