### ISSUE TITLE
IJKMediaFramework.framework with bitcode enable in Project. Archive project will false.

### ISSUE THREAD

**Issue by fighterLS** [Bilibili/ijkplayer#930]
Hi，when I used IJKMediaFramework.framework with bitcode enable in my project，build is success ,but archive is false. And the clang error is the following.

`bitcode bundle could not be generated because '/Users/IJKMovie/IJKMediaFramework.framework/IJKMediaFramework(IJKAVMoviePlayerController.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7.`

Thank you for reading.

**Comment by bbcallen** [comment]
Can not reproduce.
Make sure you have clean old build including FFmpeg.

**Comment by Tony89** [comment]
I built with Xcode 8.2.1 and got the same issue. Can you help me resolve it?

**Comment by king418** [comment]
I archived with Xcode 8.3 and got ths same issue.how did you resolve it,can you help me?

**Comment by hongzhou85** [comment]
Hi Any update with this issue?

**Comment by s366315** [comment]
I have archive error too

**Comment by lawlietop123** [comment]
I have archive error too

**Comment by lawlietop123** [comment]
@bbcallen

**Comment by ajjing** [comment]
I was able to fix this by adding "-fembed-bitcode" to Other C Flags of the project I am building a static lib of. It will give you a warning because a normal build adds "-fembed-bitcode-marker" but -fembed-bitcode takes precedence over the dummy marker

[](https://www.jianshu.com/p/8e198e8e993a)

**Comment by nikusingla** [comment]
Facing same issue, @bbcallen please help out in this, I used pods to implement ijkplayer in my project. While building it for debugging running well but while creating archive it is showing me this same error.

bitcode bundle could not be generated because '/Users/niku/Projects/Quizon/Pods/ijkplayer/IJKMediaFramework.framework/IJKMediaFramework(IJKAVMoviePlayerController.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/Users/niku/Projects/Quizon/Pods/ijkplayer/IJKMediaFramework.framework/IJKMediaFramework' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
